
spring:
  profiles:
    active: dev		#multiple=>     active: pro, dbConf
  thymeleaf:
    mode: HTML
    
book:
  name: 互聯網世界觀
  author: 李善友
  isbn: ${random.uuid}
  description: ${book.name}, 這本書美麥?