
server:
  port: 8080
#  servlet:
#    context-path: /api

logging:
  level:
    root: WARN
    com:
      example: DEBUG
  file: logs/my.log

book:
  name: 互聯網世界觀
  author: 李善友
  isbn: ${random.uuid}
  description: ${book.name}, 這本書美麥?